services:
    bvisonl.service.sessionInactivityHandler:
        class: Bvisonl\InactivityBundle\Service\SessionInactivityHandler
        arguments: ["@service_container", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
